image: docker:stable

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- apk add --update make
- docker info

stages:
- build
- release

build_development:
  stage: build
  script:
  - make docker_build_dev

build_stable:
  stage: build
  script:
  - make docker_build

release_development:
  stage: release
  script:
  - make docker_push_dev

release_production:
  stage: release
  script:
  - make docker_push
