image: docker:stable

variables:
  CONTAINER_TEST_IMAGE: circleeh/pocketmine:$CI_COMMIT_REF_NAME
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- apk add --update make curl jq git
- docker info

stages:
- Alpha
- Development

build_development:
  stage: Alpha
  script:
  - make docker_build_dev
  - make docker_push_dev

build_stable:
  stage: Development
  script:
  - make docker_build
  - make docker_push
