image: docker:stable

variables:
  CONTAINER_TEST_IMAGE: circleeh/pocketmine:$CI_COMMIT_REF_NAME
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- apk add --update make curl jq git
- docker info

stages:
- Alpha
- Beta
- Development
- Stable

build_alpha:
  stage: Alpha
  script:
  - make docker_build
  - make docker_push

build_beta:
  stage: Beta
  script:
  - make docker_build_beta
  - make docker_push_beta

build_development:
  stage: Development
  script:
  - make docker_build_dev
  - make docker_push_dev

build_stable:
  stage: Stable
  script:
  - make docker_build_stable
  - make docker_push_stable
